import { stringify } from 'yaml';
import type { SiteConfig } from '../site-config.schema';
import { buildCmsCollections, type CmsField } from './model';

// Decap-format config — read by Sveltia CMS, ADR-5's on-domain alternative
// (ground-up rewrite that reads Decap's config format, so this is the one
// generator both consume). Served at /admin/config.yml; the editor itself
// lives at /admin (public/admin/index.html, loading Sveltia's script).
//
// local_backend: true also makes this config double as Tier 1 (spec.md
// §6): `npx decap-server` (or the compatible `npm run cms` script) plus
// /admin gives a local editor with no login and no network, no separate
// config needed.

const WIDGET_MAP: Record<CmsField['type'], string> = {
  string: 'string',
  text: 'text',
  markdown: 'markdown',
  date: 'datetime',
  boolean: 'boolean',
  image: 'image',
  tags: 'list',
};

function toDecapField(field: CmsField): Record<string, unknown> {
  const out: Record<string, unknown> = {
    name: field.name,
    label: field.label,
    widget: WIDGET_MAP[field.type],
    required: Boolean(field.required),
  };
  if (field.type === 'tags') {
    out.field = { name: 'tag', label: 'Tag', widget: 'string' };
  }
  if (field.type === 'date') {
    out.time_format = false;
  }
  if (field.description) out.hint = field.description;
  return out;
}

export function generateDecapConfig(siteConfig: SiteConfig): string {
  const collections = buildCmsCollections(siteConfig);

  const config: Record<string, unknown> = {
    backend: siteConfig.repository
      ? { name: 'github', repo: siteConfig.repository, branch: 'main' }
      : {
          name: 'github',
          // No site.config.ts `repository` set yet — fill this in before
          // the hosted (non-local) path will work.
          repo: 'OWNER/REPO',
          branch: 'main',
        },
    local_backend: true,
    media_folder: 'public/images',
    public_folder: '/images',
    collections: collections.map((collection) => ({
      name: collection.name,
      label: collection.label,
      folder: collection.path,
      create: true,
      delete: true,
      slug: '{{title}}',
      extension: 'md',
      format: 'frontmatter',
      fields: collection.fields
        .filter((field) => field.name !== 'body') // Decap's body is implicit for frontmatter formats.
        .map(toDecapField),
    })),
  };

  return [
    '# Generated by `npm run cms:generate` from site.config.ts — do not hand-edit.',
    '# Read by Sveltia CMS (public/admin/index.html) and by `npx decap-server` for local editing.',
    !siteConfig.repository &&
      '# NOTE: site.config.ts has no `repository` set — the "OWNER/REPO" backend below',
    !siteConfig.repository &&
      '# needs a real value before the hosted (non-local) editor will work.',
    stringify(config, { lineWidth: 0 }),
  ]
    .filter(Boolean)
    .join('\n');
}
