import { stringify } from 'yaml';
import type { SiteConfig } from '../site-config.schema';
import { buildCmsCollections, type CmsField } from './model';

// Pages CMS (ADR-5's hosted default — app.pagescms.org, zero setup for the
// writer beyond logging in with GitHub). Reads .pages.yml from the repo
// root; the repo identity itself comes from which repo the writer connects
// there, never from a value in this file.

const TYPE_MAP: Record<CmsField['type'], string> = {
  string: 'string',
  text: 'text',
  markdown: 'rich-text',
  date: 'date',
  boolean: 'boolean',
  image: 'image',
  tags: 'string',
};

function toPagesCmsField(field: CmsField): Record<string, unknown> {
  const out: Record<string, unknown> = {
    name: field.name,
    label: field.label,
    type: TYPE_MAP[field.type],
  };
  if (field.type === 'tags') out.list = true;
  if (field.required) out.required = true;
  if (field.description) out.description = field.description;
  return out;
}

export function generatePagesCmsConfig(siteConfig: SiteConfig): string {
  const collections = buildCmsCollections(siteConfig);

  const config = {
    media: { input: 'public/images', output: '/images' },
    content: collections.map((collection) => ({
      name: collection.name,
      label: collection.label,
      type: 'collection',
      path: collection.path,
      // NFC-normalized, non-Latin-safe filenames matter here too (spec.md
      // §17) — Pages CMS slugifies {title} itself; a writer who wants a
      // stable URL independent of that sets the `slug` field, which our
      // own content schema honors regardless of the physical filename.
      filename: '{title}.md',
      format: 'yaml-frontmatter',
      fields: collection.fields.map(toPagesCmsField),
    })),
  };

  return [
    '# Generated by `npm run cms:generate` from site.config.ts — do not hand-edit.',
    '# Reference: https://pagescms.org/docs/configuration',
    stringify(config, { lineWidth: 0 }),
  ].join('\n');
}
